# Generated by Django 3.0.4 on 2020-03-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_budget_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expense',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
