# Generated by Django 3.0.4 on 2020-03-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200321_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='length',
            field=models.CharField(choices=[('W', 'Week'), ('M', 'Month'), ('Y', 'Year')], default=('M', 'Month'), max_length=5),
        ),
    ]
