# Generated by Django 3.0.4 on 2020-03-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200323_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='length',
            field=models.CharField(choices=[('Week', 'Week'), ('Month', 'Month'), ('Year', 'Year')], default='Month', max_length=5),
        ),
    ]
